#!/bin/bash
# equirement
# Install:
# nginx
# mysql
# docker
# Using:
# loop
# validate function
USER=$(id -u)
if [ $USER -ne 0 ]; then
echo "Run script $0 with ROOT or sudo"
exit 1
fi
echo "enter package name to install"
for package in $@
do
    dnf list installed $package
    if [ $? -eq 0 ]; then
        echo " $package alreday installed ...SKIPPING"
        else
        echo "$package installing"
        dnf install $package -y
    fi

done